import { contractIndexToIdentity } from "@qubic.org/crypto";
import { buildQearnUnlockInput } from "@qubic.org/contracts";
import { describe, expect, test } from "bun:test";

import { formatContractInvocation, identifyContractInvocation, isSmartContractCall, transactionTypeLabel } from "../contracts";

function base64ForByteLength(length: number): string {
  return btoa(String.fromCharCode(...new Uint8Array(length)));
}

function base64ForBytes(bytes: Uint8Array): string {
  return btoa(String.fromCharCode(...bytes));
}

test("classifies input type zero as a normal transfer", () => {
  expect(isSmartContractCall(0)).toBe(false);
  expect(isSmartContractCall(1)).toBe(true);
  expect(isSmartContractCall(-1)).toBe(false);
  expect(isSmartContractCall(undefined)).toBe(false);
});

test("labels input type zero as a transfer without relabeling smart-contract calls", () => {
  expect(transactionTypeLabel(0)).toBe("Transfer");
  expect(transactionTypeLabel(1)).toBe("Smart-contract call");
  expect(transactionTypeLabel(undefined)).toBe("Input type not reported");
});

describe("contract invocation metadata", () => {
  test("recognizes a generated Qearn procedure from RPC transaction fields", () => {
    const invocation = identifyContractInvocation({
      destination: contractIndexToIdentity(9),
      inputType: 2,
      inputSize: 12,
      inputData: base64ForByteLength(12),
    });

    expect(invocation).toEqual({
      status: "recognized",
      contractIndex: 9,
      contractName: "Qearn",
      procedureName: "Unlock",
      inputType: 2,
      inputSize: 12,
      payloadSize: 12,
      argumentDecoding: { status: "unavailable", reason: "epoch" },
    });
    expect(formatContractInvocation(invocation)).toEqual({
      title: "Unlock",
      description: "Qearn",
      metadata: "Contract index 9 · input type 2 · 12 reported bytes · 12 payload bytes",
      availability: {
        title: "Arguments unavailable",
        description: "Not decoded: the transaction epoch is not reported.",
        provenance: "Source: @qubic.org/registry/registry.json bundled with this explorer.",
      },
    });
  });

  test("decodes a payload generated by the official Qearn input builder", () => {
    const request = buildQearnUnlockInput({ amount: BigInt("123456789"), lockedEpoch: 456 });
    const invocation = identifyContractInvocation({
      destination: contractIndexToIdentity(request.contractIndex),
      inputType: request.inputType,
      inputSize: request.payload.byteLength,
      inputData: base64ForBytes(request.payload),
      epoch: 144,
    });

    expect(invocation).toEqual({
      status: "recognized",
      contractIndex: 9,
      contractName: "Qearn",
      procedureName: "Unlock",
      inputType: 2,
      inputSize: 12,
      payloadSize: 12,
      argumentDecoding: {
        status: "decoded",
        epoch: 144,
        arguments: [
          { name: "amount", value: "123456789" },
          { name: "lockedEpoch", value: "456" },
        ],
      },
    });
    expect(formatContractInvocation(invocation)).toEqual({
      title: "Unlock",
      description: "Qearn",
      metadata: "Contract index 9 · input type 2 · 12 reported bytes · 12 payload bytes",
      availability: {
        title: "2 arguments decoded",
        description: "Decoded with the installed official ABI for transaction epoch 144.",
        provenance: "Source: @qubic.org/registry/registry.json bundled with this explorer; matched transaction epoch 144.",
      },
    });
  });

  test("does not classify generated query functions as transaction procedures", () => {
    const invocation = identifyContractInvocation({
      destination: contractIndexToIdentity(9),
      inputType: 3,
      inputSize: 4,
      inputData: base64ForByteLength(4),
    });

    expect(invocation).toEqual({
      status: "unknown",
      reason: "input-type",
      contractName: "Qearn",
      contractIndex: 9,
      inputType: 3,
    });
  });

  test("recognizes procedures without an input builder when the generated decoder identifies them", () => {
    const invocation = identifyContractInvocation({
      destination: contractIndexToIdentity(28),
      inputType: 9,
      inputSize: 0,
      inputData: "",
      epoch: 144,
    });

    expect(invocation).toMatchObject({
      status: "recognized",
      contractName: "GGWP",
      procedureName: "Finalize Unstake",
      inputType: 9,
      payloadSize: 0,
      argumentDecoding: { status: "unavailable", reason: "abi" },
    });
  });

  test("keeps an opaque payload when the official registry ABI size does not match", () => {
    const invocation = identifyContractInvocation({
      destination: contractIndexToIdentity(9),
      inputType: 2,
      inputSize: 14,
      inputData: base64ForByteLength(13),
      epoch: 144,
    });

    expect(invocation).toMatchObject({
      status: "invalid",
      reason: "input-size",
    });

    const withoutReportedSize = identifyContractInvocation({
      destination: contractIndexToIdentity(9),
      inputType: 2,
      inputData: base64ForByteLength(13),
      epoch: 144,
    });
    expect(withoutReportedSize).toMatchObject({
      status: "recognized",
      argumentDecoding: { status: "unavailable", reason: "payload-size" },
    });
  });

  test("does not decode against a registry that may be stale for the transaction epoch", () => {
    const request = buildQearnUnlockInput({ amount: BigInt(1), lockedEpoch: 2 });
    const invocation = identifyContractInvocation({
      destination: contractIndexToIdentity(request.contractIndex),
      inputType: request.inputType,
      inputSize: request.payload.byteLength,
      inputData: base64ForBytes(request.payload),
      epoch: 145,
    });

    expect(invocation).toMatchObject({
      status: "recognized",
      argumentDecoding: { status: "unavailable", reason: "registry-stale" },
    });

    const display = formatContractInvocation(invocation);
    expect(display).toEqual({
      title: "Unlock",
      description: "Qearn",
      metadata: "Contract index 9 · input type 2 · 12 reported bytes · 12 payload bytes",
      availability: {
        title: "Arguments unavailable",
        description: "Not decoded: the installed official registry may be stale for this transaction epoch.",
        provenance: "Source: @qubic.org/registry/registry.json bundled with this explorer; potentially stale ABIs are never used.",
      },
    });
    expect(display.metadata).not.toContain("decoded bytes");
  });

  test("does not guess for an unrecognized contract destination", () => {
    const invocation = identifyContractInvocation({
      destination: contractIndexToIdentity(100),
      inputType: 1,
      inputData: "",
    });

    expect(invocation).toEqual({ status: "unknown", reason: "destination" });
    expect(formatContractInvocation(invocation).title).toBe("Unrecognized contract invocation");
  });

  test("does not guess for an unknown procedure on a known contract", () => {
    const invocation = identifyContractInvocation({
      destination: contractIndexToIdentity(9),
      inputType: 99,
      inputData: "",
    });

    expect(invocation).toEqual({
      status: "unknown",
      reason: "input-type",
      contractName: "Qearn",
      contractIndex: 9,
      inputType: 99,
    });
  });

  test("reports invalid base64 instead of decoding guessed data", () => {
    const invocation = identifyContractInvocation({
      destination: contractIndexToIdentity(9),
      inputType: 2,
      inputData: "not base64",
    });

    expect(invocation).toMatchObject({
      status: "invalid",
      reason: "input-data",
      contractName: "Qearn",
      procedureName: "Unlock",
    });
    expect(formatContractInvocation(invocation).title).toBe("Contract invocation unavailable");
  });

  test("reports a payload size mismatch as invalid data", () => {
    const invocation = identifyContractInvocation({
      destination: contractIndexToIdentity(9),
      inputType: 2,
      inputSize: 11,
      inputData: base64ForByteLength(12),
    });

    expect(invocation).toMatchObject({ status: "invalid", reason: "input-size" });
  });

  test("reports missing RPC fields as unavailable", () => {
    expect(identifyContractInvocation({})).toEqual({ status: "unavailable", reason: "destination" });
    expect(
      identifyContractInvocation({ destination: contractIndexToIdentity(9) }),
    ).toEqual({ status: "unavailable", reason: "input-type" });
  });
});
